#!/usr/bin/env python
import sys
import zlib
try:
    sys.stdout = sys.stdout.detach()
    sys.stdin = sys.stdin.detach()
except:
    pass
try:
    lvl = int(sys.argv[1])
except IndexError:
    lvl = zlib.Z_DEFAULT_COMPRESSION
sys.stdout.write(zlib.compress(sys.stdin.read(), lvl))
